# Numpy Practice


In [32]:
import numpy as np

## Creating array from a list

In [33]:
arr_od= np.array(1)
print("Array 0-d = ",arr_od)
arr_1d= np.array([1,2,3,4])
print("Array 1-D =", arr_1d)
arr_2d=np.array([
    [1,2,3],
    [4,5,6]
])
print("Array 2-D=",arr_2d)

Array 0-d =  1
Array 1-D = [1 2 3 4]
Array 2-D= [[1 2 3]
 [4 5 6]]


## List vs NumPy array ( Speed)

In [34]:
import time
start= time.time()
py_list= [i*2 for i in range(1000000)]
end= time.time()
print("\n List Operation time =",end-start)

start= time.time()
numpy_arr= np.arange(1000000)*2
print("\n Numpy operation time =", time.time()-start)


 List Operation time = 0.2803831100463867

 Numpy operation time = 0.017426490783691406


In [35]:
a = np.zeros((2,3,4))
print(a)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Creating Array from Scratch 

In [36]:
zero_array= np.zeros((3,3),dtype=int)
print(zero_array)

ones_array = np.ones((3,3),dtype=int)
print("\n",ones_array)

full_array= np.full((3,2), 69)
print("\n", full_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

 [[1 1 1]
 [1 1 1]
 [1 1 1]]

 [[69 69]
 [69 69]
 [69 69]]


### Numpy Random 

In [37]:
a = np.random.rand(3,2).round(3)
print(a)

b=np.random.randint(1,70,(4,4))
print("\n",b)

[[0.55  0.265]
 [0.903 0.298]
 [0.872 0.404]]

 [[52  6 45 12]
 [ 5 64 18 45]
 [14 22 32 15]
 [29 65 28  4]]


## Tensor in NUMPy

In [38]:
t1 = np.array([1, 2, 3, 4])
print("1D tensor:\n", t1)
print("shape:", t1.shape)

t2 = np.array([[1, 2, 3],
               [4, 5, 6]])
print("\n 2D tensor:\n", t2)
print("shape:", t2.shape)

t3 = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("\n 3D tensor:\n", t3)
print("shape:", t3.shape)




1D tensor:
 [1 2 3 4]
shape: (4,)

 2D tensor:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)

 3D tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape: (2, 2, 3)
